# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(901, 641)
        Form.setMinimumSize(QtCore.QSize(901, 641))
        Form.setMaximumSize(QtCore.QSize(901, 641))
        self.lbl_bg = QtWidgets.QLabel(Form)
        self.lbl_bg.setEnabled(False)
        self.lbl_bg.setGeometry(QtCore.QRect(0, 0, 901, 641))
        self.lbl_bg.setMaximumSize(QtCore.QSize(16777215, 641))
        self.lbl_bg.setAutoFillBackground(False)
        self.lbl_bg.setStyleSheet("QLabel{\n"
"    background-color: rgb(72,60,108);\n"
"}")
        self.lbl_bg.setText("")
        self.lbl_bg.setScaledContents(False)
        self.lbl_bg.setObjectName("lbl_bg")
        self.lbl_l = QtWidgets.QLabel(Form)
        self.lbl_l.setGeometry(QtCore.QRect(0, 0, 251, 641))
        self.lbl_l.setStyleSheet("QLabel{\n"
"    background-color: rgb(100,94,135);\n"
"}")
        self.lbl_l.setText("")
        self.lbl_l.setObjectName("lbl_l")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(270, 150, 611, 471))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(460, 50, 251, 41))
        self.label.setStyleSheet("font: 24pt \"Heiti SC\";\n"
"color : rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.pB_getL = QtWidgets.QPushButton(Form)
        self.pB_getL.setEnabled(True)
        self.pB_getL.setGeometry(QtCore.QRect(780, 50, 91, 41))
        self.pB_getL.setMinimumSize(QtCore.QSize(0, 0))
        self.pB_getL.setMaximumSize(QtCore.QSize(98, 100))
        self.pB_getL.setSizeIncrement(QtCore.QSize(75, 50))
        self.pB_getL.setStyleSheet("QPushButton{\n"
"    font: 14pt \"Hannotate SC\";\n"
"    background-color: rgb(224,124,106);\n"
"    border-radius:5px;\n"
"    color:white\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(234,172,91);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(220,83,129);\n"
"}")
        self.pB_getL.setObjectName("pB_getL")
        self.getList_2 = QtWidgets.QPushButton(Form)
        self.getList_2.setEnabled(True)
        self.getList_2.setGeometry(QtCore.QRect(240, 0, 98, 41))
        self.getList_2.setMinimumSize(QtCore.QSize(0, 0))
        self.getList_2.setMaximumSize(QtCore.QSize(98, 100))
        self.getList_2.setSizeIncrement(QtCore.QSize(75, 50))
        self.getList_2.setStyleSheet("QPushButton{\n"
"    font: 14pt \"Hannotate SC\";\n"
"    background-color: rgb(100,94,135);\n"
"    border-radius:20px;\n"
"    color:white\n"
"}\n"
"")
        self.getList_2.setObjectName("getList_2")
        self.pB_cP1 = QtWidgets.QPushButton(Form)
        self.pB_cP1.setEnabled(True)
        self.pB_cP1.setGeometry(QtCore.QRect(240, 50, 98, 41))
        self.pB_cP1.setMinimumSize(QtCore.QSize(0, 0))
        self.pB_cP1.setMaximumSize(QtCore.QSize(98, 100))
        self.pB_cP1.setSizeIncrement(QtCore.QSize(75, 50))
        self.pB_cP1.setStyleSheet("QPushButton{\n"
"    font: 14pt \"Hannotate SC\";\n"
"    background-color: rgb(224,124,106);\n"
"    border-radius:20px;\n"
"    color:white\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(234,172,91);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(220,83,129);\n"
"}")
        self.pB_cP1.setObjectName("pB_cP1")
        self.pB_cP2 = QtWidgets.QPushButton(Form)
        self.pB_cP2.setEnabled(True)
        self.pB_cP2.setGeometry(QtCore.QRect(240, 100, 98, 41))
        self.pB_cP2.setMinimumSize(QtCore.QSize(0, 0))
        self.pB_cP2.setMaximumSize(QtCore.QSize(98, 100))
        self.pB_cP2.setSizeIncrement(QtCore.QSize(75, 50))
        self.pB_cP2.setStyleSheet("QPushButton{\n"
"    font: 14pt \"Hannotate SC\";\n"
"    background-color: rgb(224,124,106);\n"
"    border-radius:20px;\n"
"    color:white\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(234,172,91);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(220,83,129);\n"
"}")
        self.pB_cP2.setObjectName("pB_cP2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 191, 391))
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color: rgb(140,142,173);\n"
"    border-radius:20px;\n"
"    color:white\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 450, 191, 171))
        self.label_3.setStyleSheet("QLabel{\n"
"    background-color: rgb(140,142,173);\n"
"    border-radius:20px;\n"
"    color:white\n"
"}\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 60, 171, 21))
        self.label_4.setStyleSheet("font: 16pt \"Heiti SC\";\n"
"color : rgb(255,217,102);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 140, 41, 16))
        self.label_5.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: white")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(50, 160, 41, 16))
        self.label_6.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: white")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(50, 120, 81, 16))
        self.label_7.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: white")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(40, 90, 91, 16))
        self.label_8.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: rgb(255,217,102)")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(50, 180, 61, 16))
        self.label_9.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: white")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(50, 200, 61, 16))
        self.label_10.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: white")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(50, 220, 61, 16))
        self.label_11.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: white")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(50, 240, 61, 16))
        self.label_12.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: white")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(50, 280, 31, 16))
        self.label_13.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: white")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(40, 320, 91, 16))
        self.label_14.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: rgb(255,217,102)")
        self.label_14.setObjectName("label_14")
        self.pB_openfile = QtWidgets.QPushButton(Form)
        self.pB_openfile.setGeometry(QtCore.QRect(50, 340, 91, 31))
        self.pB_openfile.setObjectName("pB_openfile")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(40, 460, 171, 21))
        self.label_16.setStyleSheet("font: 16pt \"Heiti SC\";\n"
"color : rgb(255,217,102);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(40, 490, 91, 16))
        self.label_17.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: rgb(255,217,102)")
        self.label_17.setObjectName("label_17")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(50, 530, 41, 16))
        self.label_15.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: white")
        self.label_15.setObjectName("label_15")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(50, 550, 41, 16))
        self.label_18.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: white")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(50, 510, 81, 16))
        self.label_19.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: white")
        self.label_19.setObjectName("label_19")
        self.pB_deleteTicket = QtWidgets.QPushButton(Form)
        self.pB_deleteTicket.setGeometry(QtCore.QRect(130, 590, 81, 21))
        self.pB_deleteTicket.setStyleSheet("QPushButton{\n"
"    font: 14pt \"Heiti SC\";\n"
"    border-radius:10px;\n"
"    color:white\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255,217,102);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(46,49,146);\n"
"}")
        self.pB_deleteTicket.setObjectName("pB_deleteTicket")
        self.pB_insertTicket = QtWidgets.QPushButton(Form)
        self.pB_insertTicket.setGeometry(QtCore.QRect(130, 400, 81, 21))
        self.pB_insertTicket.setStyleSheet("QPushButton{\n"
"    font: 14pt \"Heiti SC\";\n"
"    border-radius:10px;\n"
"    color:white\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255,217,102);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(46,49,146);\n"
"}")
        self.pB_insertTicket.setObjectName("pB_insertTicket")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(130, 120, 81, 16))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(100, 140, 111, 16))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(100, 160, 111, 16))
        self.textEdit_3.setObjectName("textEdit_3")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(110, 240, 101, 21))
        self.spinBox.setMaximum(1234567)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(60, 260, 151, 16))
        self.label_20.setStyleSheet("font: 12pt \"Hannotate SC\";\n"
"color: white")
        self.label_20.setObjectName("label_20")
        self.spinBox_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_2.setGeometry(QtCore.QRect(80, 280, 131, 21))
        self.spinBox_2.setMaximum(10000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.textEdit_5 = QtWidgets.QTextEdit(Form)
        self.textEdit_5.setGeometry(QtCore.QRect(100, 550, 111, 16))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(Form)
        self.textEdit_6.setGeometry(QtCore.QRect(100, 530, 111, 16))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(Form)
        self.textEdit_7.setGeometry(QtCore.QRect(130, 510, 81, 16))
        self.textEdit_7.setObjectName("textEdit_7")
        self.timeEdit = QtWidgets.QTimeEdit(Form)
        self.timeEdit.setGeometry(QtCore.QRect(110, 200, 101, 21))
        self.timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.AmPmSection)
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit_2 = QtWidgets.QTimeEdit(Form)
        self.timeEdit_2.setGeometry(QtCore.QRect(110, 220, 101, 21))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(110, 180, 104, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pB_insertTicket_2 = QtWidgets.QPushButton(Form)
        self.pB_insertTicket_2.setGeometry(QtCore.QRect(130, 310, 81, 21))
        self.pB_insertTicket_2.setStyleSheet("QPushButton{\n"
"    font: 14pt \"Heiti SC\";\n"
"    border-radius:10px;\n"
"    color:white\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255,217,102);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(46,49,146);\n"
"}")
        self.pB_insertTicket_2.setObjectName("pB_insertTicket_2")
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setGeometry(QtCore.QRect(50, 370, 151, 21))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(50, 570, 61, 16))
        self.label_21.setStyleSheet("font: 14pt \"Hannotate SC\";\n"
"color: white")
        self.label_21.setObjectName("label_21")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 570, 101, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lbl_bg.raise_()
        self.tableWidget.raise_()
        self.label.raise_()
        self.pB_getL.raise_()
        self.getList_2.raise_()
        self.pB_cP1.raise_()
        self.pB_cP2.raise_()
        self.lbl_l.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_14.raise_()
        self.pB_openfile.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_15.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.pB_deleteTicket.raise_()
        self.pB_insertTicket.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.textEdit_3.raise_()
        self.spinBox.raise_()
        self.label_20.raise_()
        self.label_13.raise_()
        self.spinBox_2.raise_()
        self.textEdit_5.raise_()
        self.textEdit_6.raise_()
        self.textEdit_7.raise_()
        self.timeEdit.raise_()
        self.timeEdit_2.raise_()
        self.comboBox.raise_()
        self.pB_insertTicket_2.raise_()
        self.textEdit_4.raise_()
        self.label_21.raise_()
        self.comboBox_2.raise_()

        self.retranslateUi(Form)
        self.pB_getL.clicked.connect(Form.getList)
        self.pB_cP1.clicked.connect(Form.switchQuery)
        self.pB_cP2.clicked.connect(Form.switchRecord)
        self.pB_openfile.clicked.connect(Form.openFile)
        self.pB_insertTicket.clicked.connect(Form.insertTicketfile)
        self.pB_deleteTicket.clicked.connect(Form.deleteTicket)
        self.pB_insertTicket_2.clicked.connect(Form.insertTicket)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "车次/航班号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "出发地"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "目的地"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "交通方式"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "出发时间"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "到达时间"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "乘车时长"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "班次信息（周）"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "票价"))
        self.label.setText(_translate("Form", "🌞火车/飞机时刻表🌞"))
        self.pB_getL.setText(_translate("Form", "完整时刻表"))
        self.getList_2.setText(_translate("Form", "修改时刻表"))
        self.pB_cP1.setText(_translate("Form", "查询路线"))
        self.pB_cP2.setText(_translate("Form", "历史记录"))
        self.label_4.setText(_translate("Form", "====插入车票信息===="))
        self.label_5.setText(_translate("Form", "出发地"))
        self.label_6.setText(_translate("Form", "目的地"))
        self.label_7.setText(_translate("Form", "车次/航班号"))
        self.label_8.setText(_translate("Form", "🌞 手动插入"))
        self.label_9.setText(_translate("Form", "交通方式"))
        self.label_10.setText(_translate("Form", "出发时间"))
        self.label_11.setText(_translate("Form", "到达时间"))
        self.label_12.setText(_translate("Form", "班次信息"))
        self.label_13.setText(_translate("Form", "票价"))
        self.label_14.setText(_translate("Form", "🌞 文件输入"))
        self.pB_openfile.setText(_translate("Form", "打开文件..."))
        self.label_16.setText(_translate("Form", "====删除车票信息===="))
        self.label_17.setText(_translate("Form", "🌞 车票信息"))
        self.label_15.setText(_translate("Form", "出发地"))
        self.label_18.setText(_translate("Form", "目的地"))
        self.label_19.setText(_translate("Form", "车次/航班号"))
        self.pB_deleteTicket.setText(_translate("Form", "删除车票"))
        self.pB_insertTicket.setText(_translate("Form", "插入车票"))
        self.label_20.setText(_translate("Form", "注：直接输入对应的星期数"))
        self.timeEdit.setDisplayFormat(_translate("Form", "APhh:mm"))
        self.timeEdit_2.setDisplayFormat(_translate("Form", "APhh:mm"))
        self.comboBox.setItemText(0, _translate("Form", "飞机"))
        self.comboBox.setItemText(1, _translate("Form", "火车"))
        self.pB_insertTicket_2.setText(_translate("Form", "插入车票"))
        self.label_21.setText(_translate("Form", "交通方式"))
        self.comboBox_2.setItemText(0, _translate("Form", "飞机"))
        self.comboBox_2.setItemText(1, _translate("Form", "火车"))
